
spring:
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost/tacocloud
      username: tacouser
      password: tacopassword
      driver-class-name: com.mysql.jdbc.Driver

      schema:
        - order-schema.sql
        - ingredient-schema.sql
        - taco-schema.sql
        - user-schema.sql
      data:
        - ingredients.sql

taco:
  orders:
    pageSize: 10

  discount:
    codes:
      abcdef: 10

---

spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN